"""
Shared ML Utilities for Insurance Claims Platform.

Provides sample presets, formatting helpers, and evaluation loaders.
"""

from typing import Any, Dict


def get_sample_claims() -> Dict[str, Dict[str, Any]]:
    """
    Returns verified benchmark test cases representing low-risk, medium-risk,
    and high-risk fraud profiles for testing and demonstration.
    """
    return {
        "High Potential Risk (Suspicious Total Loss)": {
            "MONTHS_AS_CUSTOMER": 228,
            "AGE": 44,
            "POLICY_STATE": "IL",
            "POLICY_CSL": "500/1000",
            "POLICY_DEDUCTIBLE": 1000,
            "POLICY_ANNUAL_PREMIUM": 1583.91,
            "UMBRELLA_LIMIT": 6000000,
            "INSURED_SEX": "MALE",
            "INSURED_EDUCATION_LEVEL": "Associate",
            "INSURED_OCCUPATION": "sales",
            "INSURED_RELATIONSHIP": "not-in-family",
            "POLICY_TENURE_MONTHS": 228,
            "POLICY_BIND_YEAR": 2014,
            "INCIDENT_TYPE": "Single Vehicle Collision",
            "COLLISION_TYPE": "Side Collision",
            "INCIDENT_SEVERITY": "Major Damage",
            "AUTHORITIES_CONTACTED": "None",
            "INCIDENT_STATE": "NY",
            "INCIDENT_CITY": "Arlington",
            "INCIDENT_HOUR_OF_THE_DAY": 2,
            "NUMBER_OF_VEHICLES_INVOLVED": 1,
            "PROPERTY_DAMAGE": "NO",
            "BODILY_INJURIES": 0,
            "WITNESSES": 0,
            "POLICE_REPORT_AVAILABLE": "NO",
            "CAPITAL_GAINS": 0,
            "CAPITAL_LOSS": -46000,
            "TOTAL_CLAIM_AMOUNT": 78500,
            "INJURY_CLAIM": 15700,
            "PROPERTY_CLAIM": 15700,
            "VEHICLE_CLAIM": 47100,
            "CLAIM_TO_PREMIUM_RATIO": 49.56,
            "AUTO_MAKE": "Saab",
            "AUTO_MODEL": "92x",
            "AUTO_YEAR": 2004,
            "VEHICLE_AGE": 11,
            "INCIDENT_YEAR": 2015,
            "INCIDENT_MONTH": 1,
        },
        "Low Potential Risk (Clear Police Report / Minor)": {
            "MONTHS_AS_CUSTOMER": 134,
            "AGE": 29,
            "POLICY_STATE": "OH",
            "POLICY_CSL": "100/300",
            "POLICY_DEDUCTIBLE": 2000,
            "POLICY_ANNUAL_PREMIUM": 1413.14,
            "UMBRELLA_LIMIT": 5000000,
            "INSURED_SEX": "FEMALE",
            "INSURED_EDUCATION_LEVEL": "PhD",
            "INSURED_OCCUPATION": "sales",
            "INSURED_RELATIONSHIP": "own-child",
            "POLICY_TENURE_MONTHS": 134,
            "POLICY_BIND_YEAR": 2000,
            "INCIDENT_TYPE": "Multi-vehicle Collision",
            "COLLISION_TYPE": "Rear Collision",
            "INCIDENT_SEVERITY": "Minor Damage",
            "AUTHORITIES_CONTACTED": "Police",
            "INCIDENT_STATE": "NY",
            "INCIDENT_CITY": "Columbus",
            "INCIDENT_HOUR_OF_THE_DAY": 14,
            "NUMBER_OF_VEHICLES_INVOLVED": 2,
            "PROPERTY_DAMAGE": "NO",
            "BODILY_INJURIES": 2,
            "WITNESSES": 3,
            "POLICE_REPORT_AVAILABLE": "YES",
            "CAPITAL_GAINS": 35100,
            "CAPITAL_LOSS": 0,
            "TOTAL_CLAIM_AMOUNT": 34650,
            "INJURY_CLAIM": 7700,
            "PROPERTY_CLAIM": 3850,
            "VEHICLE_CLAIM": 23100,
            "CLAIM_TO_PREMIUM_RATIO": 24.52,
            "AUTO_MAKE": "Dodge",
            "AUTO_MODEL": "RAM",
            "AUTO_YEAR": 2007,
            "VEHICLE_AGE": 8,
            "INCIDENT_YEAR": 2015,
            "INCIDENT_MONTH": 2,
        },
    }
